-- ============================================================================
-- Bousla — Path B schema: project↔driver assignment + commission model
--                          + trip ref/tank size/commission stamp
-- Run this in the Supabase SQL editor (after 0001, 0002, 0003).
-- All changes are additive and nullable/defaulted, so existing rows survive.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- project_drivers — which drivers operate which project.
-- The demo's "Manage drivers" modal + per-project driver table depend on this.
-- (Driver↔truck assignment still lives on trucks.assigned_driver_id; this is a
-- separate, many-to-many project staffing relation.)
-- ----------------------------------------------------------------------------
create table if not exists public.project_drivers (
  project_id  uuid not null references public.projects(id) on delete cascade,
  driver_id   uuid not null references public.drivers(id)  on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (project_id, driver_id)
);

-- "drivers on this project" is keyed by project_id (the PK prefix already
-- covers that); this index speeds the reverse "projects for this driver" lookup.
create index if not exists project_drivers_driver_idx
  on public.project_drivers (driver_id);

-- ----------------------------------------------------------------------------
-- projects — driver-commission model + demo header fields.
-- Mapping (Path B, confirmed):
--   rate_per_trip_sar  = what the CUSTOMER is billed per trip (untouched).
--   commission_mode    = 'fixed' | 'scalable' (already exists).
--   commission_value   = the driver's BASE commission per trip (SAR).
--   commission_bump_pct= scalable step %: each later trip this driver makes on
--                        this project, within the same calendar month, pays
--                        base * (1 + (n-1) * bump_pct/100). 0 for fixed.
-- ----------------------------------------------------------------------------
alter table public.projects
  add column if not exists commission_bump_pct numeric(6, 2) not null default 0;
alter table public.projects
  add column if not exists location text;
alter table public.projects
  add column if not exists location_lat double precision;
alter table public.projects
  add column if not exists location_lng double precision;
alter table public.projects
  add column if not exists description text;

-- Re-document commission_value to match the Path B mapping above. (The original
-- 0001 comment described it as both the fixed pay AND the scalable percent step;
-- that is superseded: commission_value is now the BASE commission, and the new
-- commission_bump_pct holds the scalable step %.)
comment on column public.projects.commission_value is
  'Driver base commission per trip (SAR). Fixed mode pays this flat; scalable mode uses it as the base for the per-trip bump.';
comment on column public.projects.commission_bump_pct is
  'Scalable step %: trip n pays commission_value * (1 + (n-1) * commission_bump_pct/100). 0 in fixed mode.';

-- ----------------------------------------------------------------------------
-- trips — human reference code, tank size, and the commission actually paid.
-- ref is generated by the DB (race-safe sequence); the app writes nothing.
-- commission_sar is stamped when the trip is marked Delivered (later cluster).
-- ----------------------------------------------------------------------------
create sequence if not exists public.trips_ref_seq;

alter table public.trips
  add column if not exists ref text;
alter table public.trips
  add column if not exists tank_size_m3 numeric(6, 2);
alter table public.trips
  add column if not exists commission_sar numeric(12, 2);

-- Default the ref to WT-<year>-<zero-padded sequence> on insert. Sequence is
-- monotonic (never resets) so refs stay globally unique; the year is cosmetic.
alter table public.trips
  alter column ref set default
    'WT-' || extract(year from now())::int || '-'
          || lpad(nextval('public.trips_ref_seq')::text, 4, '0');

-- Backfill refs for any rows that predate this column.
update public.trips
  set ref = 'WT-' || extract(year from created_at)::int || '-'
                  || lpad(nextval('public.trips_ref_seq')::text, 4, '0')
  where ref is null;

-- ============================================================================
-- Row Level Security — same policy as every other table: full read/write for
-- any logged-in (authenticated) user; the anon role gets nothing.
-- ============================================================================
alter table public.project_drivers enable row level security;

drop policy if exists "authenticated_all_project_drivers" on public.project_drivers;
create policy "authenticated_all_project_drivers"
  on public.project_drivers
  for all
  to authenticated
  using (true)
  with check (true);
